### ISSUE TITLE
Fix high priority issues

### ISSUE THREAD

**Issue by rkadam-infracloud** [vivek-infracloud/assignments#4]
**Security:**
- Please remove the Access key / secret key (even if its commented) from the repo, there is no way we support this way of providing credentials
https://github.com/vivek-infracloud/assignments/blob/main/terraform/modules/networking/provider.tf
- amazonkey.pub

**Clean Code**
- Try to minimise the commenting, commenting is expected only when you are trying to add explanation of the code, and not for commenting the code itself -- example
https://github.com/vivek-infracloud/assignments/blob/main/terraform/modules/networking/terraform.tf

- Every folder dont need to contain Readme file, there can be 1 at root level which explains about everything .

**Comment by deepankur797** [comment]
@vivek-infracloud Also please try to apply the following changes as well
1. Fetch the ami from data source rather than asking input from the user
2. you can use `cidrsubnet` function to calculate subnets from the given VPC network
3. Create separate security group for ec2 and RDS ; if you use only one then both ports will get open.
4. Don't expose passwords like you have done in the variable file in dataset module

**Comment by vivek-infracloud** [comment]
Please review the ansible assignment as well.
@rkadam-infracloud  @deepankur797 

https://github.com/vivek-infracloud/assignments/tree/main/ansible

**Comment by vivek-infracloud** [comment]
Removed the secret key/access key. Closing the issue.
